require:
  - rubocop-rails
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - bin/**/*
    - node_modules/**/*
  DisplayCopNames: true
  TargetRubyVersion: '2.5'
  TargetRailsVersion: '5.2'
Layout/IndentHeredoc:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Max: 125
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/HeredocDelimiterCase:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Rails/Output:
  Exclude:
    - 'config/deploy.rb'
    - 'lib/reviewit/**/*'
Rails/HelperInstanceVariable:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Security/Eval:
  Exclude:
    - lib/reviewit/lib/reviewit/api.rb
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'
    '%W': '()'
Style/StringLiterals:
  Enabled: false
