AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.1
Lint/Eval:
  Enabled: false
Metrics/LineLength:
  Max: 125
Rails/Output:
  Exclude:
    - 'lib/reviewit/**/*'
Style/Documentation:
  Enabled: false
Style/Not:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Rails/TimeZone:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
